stages:
  - build
  - test

build-car:
  - stage: build
  - mkdir build
  - cd build
  - touch car.txt
  - echo 'chasis' > car.txt
  - cat car.txt

artifacts:
  - build/

test-car:
  - stage: test
  - cd build
  - test -f car.txt
  - grep 'chasis' car.txt
