stages:
  - build
  - test

build-car:
  stage: build
  image: alpine
  script:
    - mkdir build
    - cd build
    - touch car.txt
    - echo 'chasis' > car.txt
    - cat car.txt

artifacts:
  paths: build/

test-car:
  stage: test
  image: alpine
  script:
    - cd build
    - test -f car.txt
    - grep 'chasis' car.txt
